
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: apis-guru
  description: The apis.guru REST API
spec:
  type: openapi
  lifecycle: experimental
  
  definition:
    $asyncapi: https://akshay89350.github.io/hello/
